const ROPSTEN = 'ropsten'
const RINKEBY = 'rinkeby'
const KOVAN = 'kovan'
const MAINNET = 'mainnet'
const TESTNET = 'testnet'
const LOCALHOST = 'localhost'

const MAINNET_CODE = 1
const TESTNET_CODE = 2
const ROPSTEN_CODE = 3
const RINKEYBY_CODE = 4
const KOVAN_CODE = 42

const ROPSTEN_DISPLAY_NAME = 'Ropsten'
const RINKEBY_DISPLAY_NAME = 'DEXON'
const KOVAN_DISPLAY_NAME = 'Kovan'
const MAINNET_DISPLAY_NAME = 'Main DEXON Network'
const TESTNET_DISPLAY_NAME = 'DEXON Test Network'

const TESTNET_RPC_URL = 'http://testnet.dexon.org:8545'

module.exports = {
  ROPSTEN,
  RINKEBY,
  KOVAN,
  MAINNET,
  TESTNET,
  LOCALHOST,
  MAINNET_CODE,
  TESTNET_CODE,
  ROPSTEN_CODE,
  RINKEYBY_CODE,
  KOVAN_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  TESTNET_DISPLAY_NAME,
  TESTNET_RPC_URL,
}
